services:
  - type: web
    name: staffview
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /

